#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autorun
dunst &
flameshot &
$HOME/.config/polybar/scripts/launch.sh &
xsetroot -cursor_name left_ptr &

# Wallpaper
feh --no-fehbg --bg-fill ~/Images/162.jpg

#bspc monitor -d    󰎚 󰈬 
bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer true

# Window borders
bspc config focused_border_color "#7561ae"
bspc config normal_border_color "#20254e"
bspc config borderless_monocle true
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"
bspc config border_width 5

#
# Rule
#

#bspc rule -a blueberry state=floating follow=off rectangle=420x900+750+90 desktop='^3'
bspc rule -a code desktop=^2

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 5

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# start picom
picom --config $HOME/.config/picom/picom.conf.example
